database:
  url:
    host: localhost
    port: 5432
    db: project
    schema: notificator
  credentials:
    username: lazarev
    password: 1234

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
    default-schema: ${database.url.schema}
    enabled: true
    parameters:
      schema: ${database.url.schema}
  datasource:
    url: jdbc:postgresql://${database.url.host}:${database.url.port}/${database.url.db}?currentSchema=${database.url.schema}
    username: ${database.credentials.username}
    password: ${database.credentials.password}
    driverClassName: org.postgresql.Driver
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificator-listener
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.ld.notificator.dto'
    listener:
      ack-mode: manual-immediate